name: Request a Feature
description: Propose a new feature
labels: ["enhancement"]

body:
- type: markdown
  attributes:
    value: >
      #### Thank you for your suggestion! Please ensure the feature request is not a duplicate.

- type: textarea
  attributes:
    label: Feature Description
    description: |
      Clearly describe the feature and its purpose. Include the motivation behind it.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Details
    description: |
      Add any extra details, such as examples, pseudo code, diagrams, or screenshots, to help explain the feature.

